#!/usr/bin/env bash
# Azure CDN → Azure Front Door: Terraform Migration Script
# Usage: ./migrate-script.sh
#
# Customize the configuration section below for your environment and run from
# the Terraform workspace root directory. Review the plan output before applying.
#
# Prerequisites:
#   - terraform validate must pass (HCL changes committed)
#   - Azure Portal migration completed for this environment
#   - Azure CLI logged in (az login)
#   - Terraform initialized (terraform init -upgrade)
#
set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────
# Update all values before running.

SUB="your-subscription-id"
RG="your-resource-group"
PROFILE="your-afd-profile-name"
BASE="/subscriptions/$SUB/resourceGroups/$RG/providers/Microsoft.Cdn/profiles/$PROFILE"

# ── Step 1: Validate ──────────────────────────────────────────────────────────
echo ""
echo "═══ Step 1: Validate ═══"
terraform validate
echo "✓ Validation passed"

# ── Step 2: Backup & Remove Classic State ─────────────────────────────────────
echo ""
echo "═══ Step 2: Backup state ═══"
BACKUP_FILE="state-backup-$(date +%Y%m%d-%H%M%S).json"
terraform state pull > "$BACKUP_FILE"
echo "✓ State backed up to $BACKUP_FILE"

echo ""
echo "═══ Step 2: Remove classic CDN resources from state ═══"
# Replace the resource addresses below with those from your Terraform state.
# Run `terraform state list | grep azurerm_cdn` to find all addresses.
# Each `state rm` is a no-op in Azure — it only removes Terraform tracking.
terraform state rm azurerm_cdn_profile.cdn_profile || true
terraform state rm azurerm_cdn_endpoint.endpoint_01 || true
# terraform state rm 'azurerm_cdn_endpoint_custom_domain.my_domain[0]' || true
# Add more as needed...
echo "✓ Classic CDN state removed"

# ── Step 3: Import AFD Resources ──────────────────────────────────────────────
# Import order: profile → secrets (if any) → endpoints → origin groups → origins → rule sets → rules → routes → custom domains
#
# For BIP module resources, the address is:
#   module.<module-name>.azurerm_cdn_frontdoor_<type>.<internal-name>
# Verify internal names by inspecting .terraform/modules/<module-name>/
#
# For raw (non-module) resources, the address is:
#   azurerm_cdn_frontdoor_<type>.<resource-name>

echo ""
echo "═══ Step 3: Import AFD profile ═══"
terraform import \
  'module.cdn_frontdoor_profile.azurerm_cdn_frontdoor_profile.frontdoor_profile' \
  "$BASE"

# Customer-certificate environments also need the Portal-created AFD secret:
# terraform import \
#   'azurerm_cdn_frontdoor_secret.root_domain_cert[0]' \
#   "$BASE/secrets/your-secret-name"

echo ""
echo "═══ Step 3: Import endpoint resources ═══"
# Replace endpoint, origin group, origin, rule set, route names with values
# discovered in Step 0 (az afd * list commands).

ENDPOINT_NAME="your-endpoint-name"
ORIGIN_GROUP_NAME="your-endpoint-Default"
ORIGIN_NAME="your-origin-name"
RULE_SET_NAME="MigratedYourEndpoint"
ROUTE_NAME="yourroutename"    # No hyphens — auto-generated by Portal migration

terraform import \
  'module.my_endpoint.azurerm_cdn_frontdoor_endpoint.frontdoor_endpoint' \
  "$BASE/afdEndpoints/$ENDPOINT_NAME"

terraform import \
  'module.my_endpoint.azurerm_cdn_frontdoor_origin_group.frontdoor_origin_group' \
  "$BASE/originGroups/$ORIGIN_GROUP_NAME"

terraform import \
  'module.my_endpoint.azurerm_cdn_frontdoor_origin.frontdoor_origin' \
  "$BASE/originGroups/$ORIGIN_GROUP_NAME/origins/$ORIGIN_NAME"

terraform import \
  'module.my_endpoint.azurerm_cdn_frontdoor_rule_set.rule_set' \
  "$BASE/ruleSets/$RULE_SET_NAME"

terraform import \
  'module.my_endpoint.azurerm_cdn_frontdoor_route.frontdoor_route' \
  "$BASE/afdEndpoints/$ENDPOINT_NAME/routes/$ROUTE_NAME"

# Custom domains — keyed by the map key in your HCL custom_domains = { "key" = { ... } }
# Add one import per domain.
# CUSTOM_DOMAIN_KEY="my-custom-domain"
# CUSTOM_DOMAIN_AZURE_NAME="my-custom-domain-name-in-azure"
# terraform import \
#   'module.my_endpoint.azurerm_cdn_frontdoor_custom_domain.custom_domains["$CUSTOM_DOMAIN_KEY"]' \
#   "$BASE/customDomains/$CUSTOM_DOMAIN_AZURE_NAME"

# Legacy *.azureedge.net domain (raw resource, not module-keyed)
# MIGRATED_DOMAIN_NAME="your-endpoint-Migrated"
# terraform import \
#   'azurerm_cdn_frontdoor_custom_domain.my_endpoint_migrated' \
#   "$BASE/customDomains/$MIGRATED_DOMAIN_NAME"

# Raw (non-module) resources — uncomment and adapt as needed
# terraform import \
#   'azurerm_cdn_frontdoor_endpoint.my_raw_endpoint' \
#   "$BASE/afdEndpoints/my-raw-endpoint-name"

# terraform import \
#   'azurerm_cdn_frontdoor_rule_set.my_rules' \
#   "$BASE/ruleSets/MigratedMyRawEndpoint"

# terraform import \
#   'azurerm_cdn_frontdoor_rule.my_global_rule' \
#   "$BASE/ruleSets/MigratedMyRawEndpoint/rules/Global"

echo "✓ All imports completed"

# ── Step 4: Plan ──────────────────────────────────────────────────────────────
echo ""
echo "═══ Step 4: Terraform plan ═══"
terraform plan

echo ""
echo "═══ Review checklist ═══"
echo "  Expected (accept):"
echo "    - azurerm_cdn_frontdoor_custom_domain_association creates"
echo "    - cdn_frontdoor_origin_ids drift (provider quirk)"
echo "    - identity additions only if Azure does not already have one"
echo ""
echo "  Accept as improvements:"
echo "    - forwarding_protocol: MatchRequest → HttpsOnly"
echo "    - https_redirect_enabled: false → true"
echo "    - Health probe additions"
echo ""
echo "  Check before accepting:"
echo "    - Module-internal HTTPS rule creates: import them first if Azure already has the rule"
echo "    - KV-backed cert secret drift: use the discovered secret name and certificate versionless_id"
echo ""
echo "  STOP if the plan shows any destroys — a destroy means a missed import."
echo "  Read references/plan-drift.md for full categorization."
echo ""
echo "  When satisfied: terraform apply"
